### ISSUE TITLE
Unable to download and update mods

### ISSUE THREAD

**Issue by XLDXiaolv** [mr-guard/dayz-server-manager#101]
Unable to download and update mods
![QQ图片20240203154854](https://github.com/mr-guard/dayz-server-manager/assets/156896068/d302b11b-9ed3-4443-9f49-29df3d9096d5)

**Comment by mr-guard** [comment]
This means, that the manager cannot invoke the steam API as their CA Certificate is unknown.

This might be because (among other things) you are using a http proxy, the CA of the cert is not installed or a Man-In-The-Middle attack is happening on your network...

You can manually review/add the CA of this url if you trust it:
[https://api.steampowered.com](https://api.steampowered.com)

You have to tell the nodejs runtime in the manager where to find that CA cert, by settings the respective environment vars.
Please refer to the nodejs docs for that or google it

This has nothing to do with the manager and I cannot give further support for that, as I do not know you network situation
