### ISSUE TITLE
Best Way to Get the Process ID imo

### ISSUE THREAD

**Issue by ItsKodas** [mr-guard/dayz-server-manager#24]
You can grab the Process ID based off the port the server is running on since only it can be running on the port, here's an example:

```
var PortCheck = await spawn('powershell', [`$proc = Get-Process -Id (Get-NetUDPEndpoint -LocalPort ${config.port}).OwningProcess\n`, 'Write-Output $proc.Id\n']);
PortCheck.stdout.on('data', data => {
        const PID = parseInt(data.toString().trim());
        process.kill(PID), console.log(`Killed Process ${PID} running on port ${config.port}!`);
        PortCheck.kill();
});
```

**Comment by mr-guard** [comment]
Thanks for the info

I like the simplicity but I think there would be an issue with it

When the server starts, it does not listen on the port immediately 

In case it crashes because of script errors or just takes long to start, this would not detect the process correctly.

However, I think this could be a much faster initial check. In case it fails, we could fall back to the current detection.
Would need to evaluate this tho

Btw. do you know the Linux equivalent to this?

**Comment by ItsKodas** [comment]
No idea if your program does this or not, but if you start the process as a child then you can obtain its PID, I have a similar piece of software I wrote for Space Engineers, any time the server restarts or boots, it checks for anything running on the port, it's more of a guarantee to prevent clashes with itself in the event of it becoming detached from the parent process :)

Maybe I have the wrong idea of for the issue.

**Comment by mr-guard** [comment]
closing as it is really old
