### ISSUE TITLE
Manager will not install - No popup for Steam Guard

### ISSUE THREAD

**Issue by KRDucky** [mr-guard/dayz-server-manager#73]
I am constantly stuck at the validation screen in the batch script that launches. I have accepted Steam Guard auth multiple times and frankly, the suggestion to disable Steam Guard is insulting. You want me to disable 2FA to install a game server? Why is it that I can sign into steamcmd with the 2FA code but not with your tool?

**Comment by mr-guard** [comment]
I understand your anger but I do not understand why this would be insulting..
I am actually pretty surprised by that.

This tool is meant for running DayZ servers 24/7 without human interaction.
If a mod update occurs at 3am in the morning, will you get up and enter your steam guard code for that?
That is the exact reason why I recommend using a separate account and disabling steam guard.
Grabbing the code from your emails is not an option, so there is no way to automate that.
Obviously disabling 2FA is a security concern, which is why I recommend to use a separate account with a strong password.

If you want to complain about why this is necessary at all, complain to BI about not being able to download Workshop items with the anon user. This would fix this issue all together.

It's technically possible to get the input of 2FA codes working, but because of the above reason it is not on my priority list.
I cannot and will not promise that this will work in the future

**Comment by mr-guard** [comment]
Added in v3.4.0
